name: Self-Hosted Workflow

on:
  push:
    branches:
      - main

jobs:
  remote_server_job:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tests and save log
        shell: cmd
        run: |
          cd /d D:\Personal_Workspace\CI_CD_QA\temp_qa
          echo Current directory:
          cd

          D:\Personal_Workspace\CI_CD_QA\temp_qa\venv\Scripts\python.exe --version
          D:\Personal_Workspace\CI_CD_QA\temp_qa\venv\Scripts\pip.exe list

          rem Run pytest and save all output to workflow.log
          D:\Personal_Workspace\CI_CD_QA\temp_qa\venv\Scripts\python.exe -m pytest -v --html=report.html --self-contained-html --capture=tee-sys > workflow.log 2>&1

          rem Show the log in Actions output
          type workflow.log

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: D:\Personal_Workspace\CI_CD_QA\temp_qa\report.html