name: Self-Hosted Workflow

on:
  push:
    branches:
      - main

jobs:
  remote_server_job:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Activate venv and run tests (live logs)
        shell: powershell
        run: |
          # Activate the virtual environment
          & "D:\Personal_Workspace\CI_CD_QA\temp_qa\venv\Scripts\Activate.ps1"
          
          # Move to the project directory
          Set-Location -Path "D:\Personal_Workspace\CI_CD_QA\temp_qa"

          # Print current info
          Write-Host "Current directory:"
          Get-Location
          python --version
          pip list

          # Run pytest, stream to GitHub Actions log AND save locally
          python -m pytest -v --html=report.html --self-contained-html --capture=tee-sys | Tee-Object -FilePath workflow.log

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: D:\Personal_Workspace\CI_CD_QA\temp_qa\report.html